#Update documentation using jsDocs
on:
    push:
      branches:
      - master

name: Generate does
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        
        - name: Delete old Docs
          run: rm -r ./js/documentation/*

        - name: Create new Docs
          uses: andstor/jsdoc-action@v1
          with:
            source_dir: ./src
            output_dir: ./js/documentation
            config_file: conf.json
            template: minami
            front_page: ./js/README.md