#Update documentation using jsDocs
on: push

name: Generate docs
jobs:
    build:
      name: jsDocs
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1

        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: "19" # specify the node version you want

        - name: Delete old Docs
          run: rm -rf src/js/documentation/*
        
        - name: Install jsdocs
          run: npm install -g jsdocs

        - name: Run jsdocs
          run: |
            npm run jsdoc src/js/landing.js -d src/js/documentation
            npm run jsdoc src/js/selection.js -d src/js/documentation
            npm run jsdoc src/js/tarotCards.js -d src/js/documentation