#Update documentation using jsDocs
on: push

name: Generate docs
jobs:
    build:
      name: jsDocs
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1

        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: "19" # specify the node version you want

        - name: Delete old Docs
          run: rm -rf src/js/documentation/*

        - name: Build
          uses: andstor/jsdoc-action@v1
          with:
            source_dir: ./src/js
            recurse: true
            output_dir: ./src/js/documentation