# This workflow will run eslint on our javascript file ensuring we have uniform formatting
name: Lint
on: [push]
jobs:
  build:
    name: Strict Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "19" # specify the node version you want
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run eslint:github-action
